# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190622_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1024, upload_to='', verbose_name='图片路径')),
                ('status', models.PositiveIntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图片路径',
                'verbose_name_plural': '图片路径',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id', '-pv', '-create_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1, verbose_name='浏览数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1, verbose_name='评论数'),
        ),
    ]
