# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190624_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
