# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, max_length=256, upload_to='', verbose_name='图片路径'),
        ),
    ]
