# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='正文必须为MarkDown格式', null=True, verbose_name='正文'),
        ),
    ]
