# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 01:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='正文'),
        ),
    ]
