# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190626_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
