# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 02:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190626_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=2048, verbose_name='内容'),
        ),
    ]
