# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 08:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190628_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2048, verbose_name='内容'),
        ),
    ]
